# alacritty.toml
#
# A comprehensive starter configuration for the Alacritty terminal emulator.
# Format: TOML (https://toml.io)
# For a full list of options, visit: https://alacritty.org/config-alacritty.html

# This imports other config files. Useful for splitting up your config.
# For example, you could have a separate `colors.toml` and `fonts.toml`.
# import = ["/path/to/my/other/configs.toml"]


# ==============================================================================
# Window & Appearance
# ==============================================================================
[window]
dimensions = { columns = 100, lines = 50 }

# Window padding (in pixels).
padding = { x = 10, y = 10 }
dynamic_padding = true

# Decorations: "full", "none", or "transparent".
# "none" is great for tiling window managers.
decorations = "full"

# Window startup mode: "Windowed", "Maximized", "Fullscreen".
startup_mode = "Windowed"

# Window title.
title = "Alacritty"

# Allow Alacritty to be controlled by dynamic title sequences.
dynamic_title = true

# Background opacity (0.0 to 1.0).
# You must have a compositor running for this to work (e.g., Picom, Mutter, etc.).
opacity = 1.0


# ==============================================================================
# Font Settings
# ==============================================================================
[font]
# You MUST change "JetBrains Mono Nerd Font" to a font installed on your system.
# Run `fc-list` on Linux to see available fonts.
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
#normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
#bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
#italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }

# Font size in points.
size = 11.0

# Glyphs for box drawing characters, etc.
# built_in_box_drawing = false


# ==============================================================================
# Dracula Color Scheme
# https://draculatheme.com/
# ==============================================================================
[colors]
primary = { background = "#282a36", foreground = "#f8f8f2" }
#cursor = { text = "#282a36", cursor = "#f8f8f2" }
cursor = { text = "#282a36", cursor = "#dd0000" }

[colors.normal]
  black = "#000000"
  red = "#ff5555"
  green = "#50fa7b"
  yellow = "#f1fa8c"
  blue = "#bd93f9"
  magenta = "#ff79c6"
  cyan = "#8be9fd"
  white = "#bfbfbf"

[colors.bright]
  black = "#4d4d4d"
  red = "#ff6e67"
  green = "#5af78e"
  yellow = "#f4f99d"
  blue = "#caa9fa"
  magenta = "#ff92d0"
  cyan = "#9aedfe"
  white = "#e6e6e6"


# ==============================================================================
# Keyboard & Bindings
# ==============================================================================
[keyboard]
# Key bindings. Alacritty uses the character's name for keys, and modifiers
# like "Control", "Shift", "Alt", "Super" (Windows/Command key).
bindings = [
  # (macOS) Command+C for Copy
  { key = "C", mods = "Super", action = "Copy" },
  # (macOS) Command+V for Paste
  { key = "V", mods = "Super", action = "Paste" },

  # (Linux/Windows) Ctrl+Shift+C for Copy
  { key = "C", mods = "Control|Shift", action = "Copy" },
  # (Linux/Windows) Ctrl+Shift+V for Paste
  { key = "V", mods = "Control|Shift", action = "Paste" },

  # Increase font size
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" }, # Numpad plus

  # Decrease font size
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },

  # Reset font size
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
]


# ==============================================================================
# Scrolling
# ==============================================================================
[scrolling]
# Number of lines of scrollback history to keep.
history = 10000

# Scrolling multiplier.
multiplier = 3


# ==============================================================================
# Mouse
# ==============================================================================
[mouse]
# Hide the mouse cursor when typing.
hide_when_typing = true

#[terminal]
# You can set a custom shell and arguments.
# By default, Alacritty uses the system's default shell.
# program = "/bin/fish"
# args = ["-l"]

